### ISSUE TITLE
0.1.7 not pushed to PyPI

### ISSUE THREAD

**Issue by RazerM** [orf/crontabula#18]
Sorry if you just didn't get to it, but it would be great if the 0.1.7 release could be pushed to PyPI.

**Comment by orf** [comment]
Hey, I'm really sorry about the slow response here. I've published 0.1.7 - I thought I did it previously, but it appears my token was no longer valid and I missed the error.

Thanks a lot for your contributions to this project by the way, I really appreciate it <3
